version: '3'

services:
  portserver1:
    build: .
    hostname: portserver
    #environment:
    devices:
      - "/dev/ttyUSB2:dev/ttyUSB1"
    ports:
      - "4001:2001"
    volumes:
      - ./ser2net.conf:/etc/ser2net.conf
    restart: always


  portserver2:
    build: .
    hostname: portserver
    #environment:
    devices:
      - "/dev/ttyUSB6:dev/ttyUSB1"
    ports:
      - "4002:2001"
    volumes:
      - ./ser2net.conf:/etc/ser2net.conf
    restart: always
